// Code generated by MockGen. DO NOT EDIT.
// Source: business-logic/interfaces/shortcode_generator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShortcodeGenerator is a mock of ShortcodeGenerator interface.
type MockShortcodeGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockShortcodeGeneratorMockRecorder
}

// MockShortcodeGeneratorMockRecorder is the mock recorder for MockShortcodeGenerator.
type MockShortcodeGeneratorMockRecorder struct {
	mock *MockShortcodeGenerator
}

// NewMockShortcodeGenerator creates a new mock instance.
func NewMockShortcodeGenerator(ctrl *gomock.Controller) *MockShortcodeGenerator {
	mock := &MockShortcodeGenerator{ctrl: ctrl}
	mock.recorder = &MockShortcodeGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortcodeGenerator) EXPECT() *MockShortcodeGeneratorMockRecorder {
	return m.recorder
}

// GenerateShortcode mocks base method.
func (m *MockShortcodeGenerator) GenerateShortcode() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateShortcode")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateShortcode indicates an expected call of GenerateShortcode.
func (mr *MockShortcodeGeneratorMockRecorder) GenerateShortcode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateShortcode",
		reflect.TypeOf((*MockShortcodeGenerator)(nil).GenerateShortcode))
}
