// Code generated by MockGen. DO NOT EDIT.
// Source: business-logic/interfaces/url_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/AlexL70/linkshortener/backend/business-logic/models"
	gomock "github.com/golang/mock/gomock"
)

// MockUrlRepository is a mock of UrlRepository interface.
type MockUrlRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUrlRepositoryMockRecorder
}

// MockUrlRepositoryMockRecorder is the mock recorder for MockUrlRepository.
type MockUrlRepositoryMockRecorder struct {
	mock *MockUrlRepository
}

// NewMockUrlRepository creates a new mock instance.
func NewMockUrlRepository(ctrl *gomock.Controller) *MockUrlRepository {
	mock := &MockUrlRepository{ctrl: ctrl}
	mock.recorder = &MockUrlRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlRepository) EXPECT() *MockUrlRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUrlRepository) Create(ctx context.Context, url *models.ShortenedUrl) (*models.ShortenedUrl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, url)
	ret0, _ := ret[0].(*models.ShortenedUrl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUrlRepositoryMockRecorder) Create(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUrlRepository)(nil).Create), ctx, url)
}

// FindByID mocks base method.
func (m *MockUrlRepository) FindByID(ctx context.Context, id int64) (*models.ShortenedUrl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.ShortenedUrl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUrlRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUrlRepository)(nil).FindByID), ctx, id)
}

// FindByUserID mocks base method.
func (m *MockUrlRepository) FindByUserID(ctx context.Context, userID int64, page, pageSize int) ([]*models.ShortenedUrl, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID, page, pageSize)
	ret0, _ := ret[0].([]*models.ShortenedUrl)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockUrlRepositoryMockRecorder) FindByUserID(ctx, userID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockUrlRepository)(nil).FindByUserID), ctx, userID, page, pageSize)
}

// Update mocks base method.
func (m *MockUrlRepository) Update(ctx context.Context, url *models.ShortenedUrl) (*models.ShortenedUrl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, url)
	ret0, _ := ret[0].(*models.ShortenedUrl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUrlRepositoryMockRecorder) Update(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUrlRepository)(nil).Update), ctx, url)
}
