// Code generated by MockGen. DO NOT EDIT.
// Source: business-logic/interfaces/user_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/AlexL70/linkshortener/backend/business-logic/models"
	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUserWithProvider mocks base method.
func (m *MockUserRepository) CreateUserWithProvider(ctx context.Context, userName string, up *models.UserProvider) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserWithProvider", ctx, userName, up)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserWithProvider indicates an expected call of CreateUserWithProvider.
func (mr *MockUserRepositoryMockRecorder) CreateUserWithProvider(ctx, userName, up interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserWithProvider", reflect.TypeOf((*MockUserRepository)(nil).CreateUserWithProvider), ctx, userName, up)
}

// FindByProviderEmailWithSeedID mocks base method.
func (m *MockUserRepository) FindByProviderEmailWithSeedID(ctx context.Context, provider models.Provider, email string) (*models.User, *models.UserProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProviderEmailWithSeedID", ctx, provider, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(*models.UserProvider)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByProviderEmailWithSeedID indicates an expected call of FindByProviderEmailWithSeedID.
func (mr *MockUserRepositoryMockRecorder) FindByProviderEmailWithSeedID(ctx, provider, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProviderEmailWithSeedID", reflect.TypeOf((*MockUserRepository)(nil).FindByProviderEmailWithSeedID), ctx, provider, email)
}

// FindByProviderID mocks base method.
func (m *MockUserRepository) FindByProviderID(ctx context.Context, provider models.Provider, providerUserID string) (*models.User, *models.UserProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProviderID", ctx, provider, providerUserID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(*models.UserProvider)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByProviderID indicates an expected call of FindByProviderID.
func (mr *MockUserRepositoryMockRecorder) FindByProviderID(ctx, provider, providerUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProviderID", reflect.TypeOf((*MockUserRepository)(nil).FindByProviderID), ctx, provider, providerUserID)
}

// UpdateProviderUserID mocks base method.
func (m *MockUserRepository) UpdateProviderUserID(ctx context.Context, userProviderID int64, newProviderUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProviderUserID", ctx, userProviderID, newProviderUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProviderUserID indicates an expected call of UpdateProviderUserID.
func (mr *MockUserRepositoryMockRecorder) UpdateProviderUserID(ctx, userProviderID, newProviderUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProviderUserID", reflect.TypeOf((*MockUserRepository)(nil).UpdateProviderUserID), ctx, userProviderID, newProviderUserID)
}
